# Project information 
site_name: memon_tree的个人DC小文档
#site_description:
site_author: memon_tree
site_url: https://dcdoc.313511.xyz/

# Copyright 
copyright: Built by <a href="https://313511.xyz"> memon_tree

plugins:
  - document-dates:
      position: top            # 显示位置: top(标题后) bottom(文档末尾), 默认: top
      type: date               # 日期类型: date datetime timeago, 默认: date
      exclude:                 # 排除文件列表
        - index.md
      date_format: '%Y-%m-%d'  # 日期格式化字符串（例如: %Y年%m月%d日、%b %d, %Y）
      time_format: '%H:%M:%S'  # 时间格式化字符串（仅在 type=datetime 时有效）
      show_created: true       # 显示创建日期: true false, 默认: true
      show_updated: true       # 显示最后更新日期: true false, 默认: true
      show_author: true        # 显示作者: true(头像) text(文本) false(隐藏), 默认: true
# Configuration
theme:
  name: material # 不能改
  language: zh # 中文
  # language: en # English
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github

  features:
    - navigation.tabs # 这一项将 nav 的顶级标题置顶
    - navigation.top # 返回顶部标签
    - navigation.instant # 即时加载
    - navigation.indexes # 章节索引页

# Extensions 不能改
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: false

# 目录（导航）
# 格式： - 名称: 路径（通常是相对路径）
# 使用缩进来表示子目录。
nav:
  - 首页: index.md
  - DC文档:
    - dcdocs/index.md
    - 使用手机进入服务器: dcdocs/FCL.md
    - DC个人信箱设立: dcdocs/DCpersonalMail.md
    - DC个人信箱电邮提醒: dcdocs/DCMailE.md
    - 信任权限组的获取: dcdocs/TrustGroup.md
    - 地图画自助申请相关: dcdocs/DCMAP.md
    - 常见问题: dcdocs/FAQ.md
    - 夹带私货:
        - 梦幻聚落介绍: dcdocs/MW.md
  - 好吃的唱片:
      - DeliciousMusic/index.md
      - 发行记录: DeliciousMusic/Records.md
